// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfXbXla6BVOonvUJJ8vvBDPxgS9Ur8NbQ',
    appId: '1:190028955711:web:a3177e0c62cb65c59db88a',
    messagingSenderId: '190028955711',
    projectId: 'openshelf-41bd9',
    authDomain: 'openshelf-41bd9.firebaseapp.com',
    storageBucket: 'openshelf-41bd9.firebasestorage.app',
    measurementId: 'G-JVXT4GGLYS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkUHyHxQPh24SD9DYEBaEaAoXjEtM33PQ',
    appId: '1:190028955711:android:456f865c2ea3915b9db88a',
    messagingSenderId: '190028955711',
    projectId: 'openshelf-41bd9',
    storageBucket: 'openshelf-41bd9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4rxRkk1ialiKF0bRuKxJxRs_0s8fD-KU',
    appId: '1:190028955711:ios:2cd4bd494e5e43599db88a',
    messagingSenderId: '190028955711',
    projectId: 'openshelf-41bd9',
    storageBucket: 'openshelf-41bd9.firebasestorage.app',
    iosBundleId: 'com.example.openshelfApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4rxRkk1ialiKF0bRuKxJxRs_0s8fD-KU',
    appId: '1:190028955711:ios:2cd4bd494e5e43599db88a',
    messagingSenderId: '190028955711',
    projectId: 'openshelf-41bd9',
    storageBucket: 'openshelf-41bd9.firebasestorage.app',
    iosBundleId: 'com.example.openshelfApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfXbXla6BVOonvUJJ8vvBDPxgS9Ur8NbQ',
    appId: '1:190028955711:web:f23d05c3b869b50e9db88a',
    messagingSenderId: '190028955711',
    projectId: 'openshelf-41bd9',
    authDomain: 'openshelf-41bd9.firebaseapp.com',
    storageBucket: 'openshelf-41bd9.firebasestorage.app',
    measurementId: 'G-N655H08R1V',
  );
}
